# c.f. https://dependabot.com/docs/config-file/
version: 1

update_configs:
  - package_manager: "java:maven"

    directory: "/"

    update_schedule: "monthly"

    default_assignees:
      - sue445

    allowed_updates:
      - match:
          update_type: "security"
